# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Laboratorio Nacional de Ciencias de la Sostenibilidad
author: LANCIS
email: webmaster@iecologia.unam.mx
description: > # this means to ignore newlines until "baseurl:"
  El Laboratorio Nacional de Ciencias de la Sostenibilidad impulsa
  la innovación en la investigación transdisciplinaria, la
  enseñanza, la vinculación y el desarrollo tecnológico, con el fin de
  ligar la ciencia y la toma de decisiones para facilitar el tránsito
  hacia la sostenibilidad en el país.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  sostenibilidad-unam

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - reglamentos
  - Gemfile
  - Gemfile.lock
